export const popularproductData = [
  {
    title: "Apple",
    src: "https://www.collinsdictionary.com/images/full/apple_158989157.jpg",
    sale: true,
    discount: "15%",
    category: "Fruits",
    star: 4.2,
    review: 85,
    price: 30,
    oldprice: 35,
  },
  {
    title: "Banana",
    src: "https://nutritionsource.hsph.harvard.edu/wp-content/uploads/2018/08/bananas-1354785_1920.jpg",
    sale: false,
    category: "Fruits",
    star: 3.9,
    review: 60,
    price: 18,
  },
  {
    title: "Spinach",
    src: "https://www.greendna.in/cdn/shop/files/palak2_1200x1200.jpg?v=1715600291",
    sale: true,
    discount: "10%",
    category: "Leafy Greens",
    star: 4.7,
    review: 30,
    price: 25,
    oldprice: 28,
  },
  {
    title: "Carrot",
    src: "https://m.media-amazon.com/images/I/71S6oQqVa5L._AC_UF1000,1000_QL80_.jpg",
    sale: false,
    category: "Vegetables",
    star: 4.1,
    review: 42,
    price: 22,
  },
  {
    title: "Kiwi",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4ZMp2-OchDFxpyYcRSeolEAoTKTGpoLo_IQ&s",
    sale: true,
    discount: "20%",
    category: "Fruits",
    star: 4.8,
    review: 95,
    price: 35,
    oldprice: 45,
  },
  {
    title: "Cabbage",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUQtTH8ouL1V4n0H39i9jZwR6PLBEfTPFc_Q&s",
    sale: false,
    category: "Leafy Greens",
    star: 3.5,
    review: 18,
    price: 16,
  },
  {
    title: "Orange",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-6GoLpPXoOkT0lAuFcxXwJSQ7nxtRQqVJLg&s",
    sale: true,
    discount: "25%",
    category: "Citrus",
    star: 4.6,
    review: 70,
    price: 26,
    oldprice: 35,
  },
  {
    title: "Tomato",
    src: "https://img.etimg.com/thumb/width-420,height-315,imgsize-56196,resizemode-75,msid-95423731/magazines/panache/5-reasons-why-tomatoes-should-be-your-favourite-fruit-this-year/tomatoes-canva.jpg",
    sale: false,
    category: "Vegetables",
    star: 3.8,
    review: 50,
    price: 20,
  },
  {
    title: "Grapes",
    src: "https://m.media-amazon.com/images/I/61xrIAiNe9L.jpg",
    sale: true,
    discount: "18%",
    category: "Fruits",
    star: 4.5,
    review: 66,
    price: 29,
    oldprice: 35,
  },
  {
    title: "Broccoli",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnmsTqc4RhMDFWD3kmkwhJX-zzKAAx-mdnjw&s",
    sale: false,
    category: "Vegetables",
    star: 4.0,
    review: 39,
    price: 24,
  },
  {
    title: "Pineapple",
    src: "https://organicmandya.com/cdn/shop/files/Pineapple.jpg?v=1721375225&width=1000",
    sale: true,
    discount: "12%",
    category: "Tropical",
    star: 4.3,
    review: 77,
    price: 40,
    oldprice: 45,
  },
  {
    title: "Mango",
    src: "https://static.vecteezy.com/system/resources/previews/026/795/003/non_2x/mango-fruit-tropical-transparent-png.png",
    sale: false,
    category: "Tropical",
    star: 4.9,
    review: 100,
    price: 38,
  },
  {
    title: "Potato",
    src: "https://m.media-amazon.com/images/I/41QKCkQ2A5L.jpg",
    sale: false,
    category: "Root Vegetables",
    star: 3.6,
    review: 22,
    price: 15,
  },
  {
    title: "Strawberry",
    src: "https://cdn.zeptonow.com/production/ik-seo/tr:w-640,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/08850157-9dcb-463f-825c-5b7d986f6bb3/Strawberry.jpeg",
    sale: true,
    discount: "30%",
    category: "Berries",
    star: 4.7,
    review: 81,
    price: 28,
    oldprice: 40,
  },
  {
    title: "Blueberry",
    src: "https://cdn.britannica.com/11/118211-050-DDF2A0C7/Cluster-blueberries.jpg",
    sale: true,
    discount: "10%",
    category: "Berries",
    star: 4.4,
    review: 33,
    price: 32,
    oldprice: 36,
  },
  {
    title: "Onion",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_c4mzTsqYoLWHNziM4mHQEEp6-qCek6H7bQ&s",
    sale: false,
    category: "Root Vegetables",
    star: 3.3,
    review: 27,
    price: 14,
  },
];


export const bestproductData = [
  {
    title: "Apple",
    src: "https://www.collinsdictionary.com/images/full/apple_158989157.jpg",
    sale: true,
    discount: "15%",
    category: "Fruits",
    instock: true,
    star: 4.2,
    review: 85,
    price: 30,
    oldprice: 35,
  },
  {
    title: "Banana",
    src: "https://nutritionsource.hsph.harvard.edu/wp-content/uploads/2018/08/bananas-1354785_1920.jpg",
    sale: false,
     instock: true,
    category: "Fruits",
    star: 3.9,
    review: 60,
    price: 18,
  },
  {
    title: "Spinach",
    src: "https://www.greendna.in/cdn/shop/files/palak2_1200x1200.jpg?v=1715600291",
    sale: true,
    discount: "10%",
     instock: true,
    category: "Leafy Greens",
    star: 4.7,
    review: 30,
    price: 25,
    oldprice: 28,
  },
  {
    title: "Carrot",
    src: "https://m.media-amazon.com/images/I/71S6oQqVa5L._AC_UF1000,1000_QL80_.jpg",
    sale: false,
     instock: true,
    category: "Vegetables",
    star: 4.1,
    review: 42,
    price: 22,
  },
  {
    title: "Kiwi",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4ZMp2-OchDFxpyYcRSeolEAoTKTGpoLo_IQ&s",
    sale: true, instock: true,
    discount: "20%",
    category: "Fruits",
    star: 4.8,
    review: 95,
    price: 35,
    oldprice: 45,
  },
  {
    title: "Cabbage",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUQtTH8ouL1V4n0H39i9jZwR6PLBEfTPFc_Q&s",
    sale: false, instock: true,
    category: "Leafy Greens",
    star: 3.5,
    review: 18,
    price: 16,
  },
  {
    title: "Orange",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-6GoLpPXoOkT0lAuFcxXwJSQ7nxtRQqVJLg&s",
    sale: true, instock: true,
    discount: "25%",
    category: "Citrus",
    star: 4.6,
    review: 70,
    price: 26,
    oldprice: 35,
  },
  {
    title: "Tomato",
    src: "https://img.etimg.com/thumb/width-420,height-315,imgsize-56196,resizemode-75,msid-95423731/magazines/panache/5-reasons-why-tomatoes-should-be-your-favourite-fruit-this-year/tomatoes-canva.jpg",
    sale: false, instock: true,
    category: "Vegetables",
    star: 3.8,
    review: 50,
    price: 20,
  },
  {
    title: "Grapes",
    src: "https://m.media-amazon.com/images/I/61xrIAiNe9L.jpg",
    sale: true, instock: true,
    discount: "18%",
    category: "Fruits",
    star: 4.5,
    review: 66,
    price: 29,
    oldprice: 35,
  },
  {
    title: "Broccoli",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnmsTqc4RhMDFWD3kmkwhJX-zzKAAx-mdnjw&s",
    sale: false, instock: true,
    category: "Vegetables",
    star: 4.0,
    review: 39,
    price: 24,
  },
  {
    title: "Pineapple",
    src: "https://organicmandya.com/cdn/shop/files/Pineapple.jpg?v=1721375225&width=1000",
    sale: true, instock: true,
    discount: "12%",
    category: "Tropical",
    star: 4.3,
    review: 77,
    price: 40,
    oldprice: 45,
  },
  {
    title: "Mango",
    src: "https://static.vecteezy.com/system/resources/previews/026/795/003/non_2x/mango-fruit-tropical-transparent-png.png",
    sale: false, instock: true,
    category: "Tropical",
    star: 4.9,
    review: 100,
    price: 38,
  },
  {
    title: "Potato",
    src: "https://m.media-amazon.com/images/I/41QKCkQ2A5L.jpg",
    sale: false, instock: true,
    category: "Root Vegetables",
    star: 3.6,
    review: 22,
    price: 15,
  },
  {
    title: "Strawberry",
    src: "https://cdn.zeptonow.com/production/ik-seo/tr:w-640,ar-3000-3000,pr-true,f-auto,q-80/cms/product_variant/08850157-9dcb-463f-825c-5b7d986f6bb3/Strawberry.jpeg",
    sale: true, instock: true,
    discount: "30%",
    category: "Berries",
    star: 4.7,
    review: 81,
    price: 28,
    oldprice: 40,
  },
  {
    title: "Blueberry",
    src: "https://cdn.britannica.com/11/118211-050-DDF2A0C7/Cluster-blueberries.jpg",
    sale: true, instock: true,
    discount: "10%",
    category: "Berries",
    star: 4.4,
    review: 33,
    price: 32,
    oldprice: 36,
  },
  {
    title: "Onion",
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_c4mzTsqYoLWHNziM4mHQEEp6-qCek6H7bQ&s",
    sale: false, instock: true,
    category: "Root Vegetables",
    star: 3.3,
    review: 27,
    price: 14,
  },
]